# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true   
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://127.0.0.1:49966/eureka 

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:30689/eureka/   # Use the correct service registry URL
    registerWithEureka: true   # The config server itself should not register with Eureka if unnecessary
    fetchRegistry: true         # Ensure it fetches the service registry info

      
